kashti:
  enabled: true

rbac:
  enabled: true

genericGateway:
  enabled: true
  registry: brigadecore
  name: brigade-generic-gateway
  service:
    name: brigade-generic-service
    type: ClusterIP
    externalPort: 8081
    internalPort: 8000
  serviceAccount:
    create: true
    name:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      cert-manager.io/acme-challenge-type: http01

    hosts:
      - brigadedemo.ehn.nu
    paths:
    - /
    tls:
      - secretName: brigade-events
        hosts:
        - brigadedemo.ehn.nu