replicaCount: 1

rbac:
  enabled: true

image:
  repository: radumatei/brigade-eventgrid-gateway
  tag: v0.1.6
  pullPolicy: Always

service:
  type: ClusterIP
  internalPort: 8080
  externalPort: 80


# for Azure EventGrid you must have TLS ingress
# more information here - https://docs.microsoft.com/en-us/azure/event-grid/security-authentication
ingress:
  enabled: true
  annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      cert-manager.io/acme-challenge-type: http01

  host: brigadedemo.ehn.nu
  paths:
  - /cloudevents
  tls:
    - secretName: brigadecert
      hosts:
      - brigadedemo.ehn.nu
