apiVersion: v1
kind: Secret
metadata:
  name: order-secrets
  labels:
    app: order-processor
data:
  SERVICEBUS_QUEUE_CONNECTIONSTRING: RW5kcG9pbnQ9c2I6Ly9rZWRhZGVtbzEyMy5zZXJ2aWNlYnVzLndpbmRvd3MubmV0LztTaGFyZWRBY2Nlc3NLZXlOYW1lPW9yZGVyLWNvbnN1bWVyO1NoYXJlZEFjY2Vzc0tleT1nanVRUU95YUZoN1ppKy9pVHQ3bEdLUWMzbEVXYjhlQ0ZVZ01wRkc1Z2FNPTtFbnRpdHlQYXRoPW9yZGVycwo=